[rpc_and_lcd_endpoints]
eth_rpc_endpoint = "https://goerli.prylabs.net"
bor_rpc_end_point = "http://143.110.185.126:8545"
bor_external_rpc = "http://143.110.185.126:8545"
heimdall_rpc_endpoint = "http://143.110.185.126:26657"
heimdall_lcd_endpoint = "http://143.110.185.126:1317"
heimdall_external_rpc = "http://143.110.185.126:26657"

[validator_details]
validator_hex_addr = "E4B8E9222704401AD16D4D826732953DAF07C7E2"
signer_address = "0xE4b8e9222704401aD16d4d826732953DAf07C7E2"
validator_name = "Matic"
stake_manager_contract = "0x00200eA4Ee292E253E6Ca07dBA5EdC07c8Aa37A3"

[enable_alerts]
enable_telegram_alerts = "yes"
enable_email_alerts = "no"

[daily_alert]
alert_time1 = "02:30PM"
alert_time2 = "02:30AM"

[choose_alerts]
balance_change_alerts = "yes"
voting_power_alerts = "yes"
proposal_alerts = "yes"
block_diff_alerts = "yes"
missed_block_alerts = "yes"
num_peers_alerts = "yes"
node_sync_alert = "yes"
node_status_alert = "yes"

[alerting_threholds]
num_peers_threshold = 0
missed_blocks_threshold = 10
block_diff_threshold = 10

[scraper]
rate = "6s"
port = ":8080"
validator_rate = "60s"
contract_rate = "300s"

[telegram]
tg_chat_id = 228288205
tg_bot_token = "1117273891:AAEtr3ZU5x4JRj5YSF4LBeu1fPF0T4xj-UI"

[sendgrid]
sendgrid_token = "SG.J4dl16RST9OM9Nc2Tbvh6A.L_FPSzlqvBesPPQ06XGhVTTEt5Hs8TUzo9D1AZlRk"
email_address = "xyz@domain.com"

[influxdb]
port = "8086"
database = "matic3"
username = "vitwit"